version: '3'
services:
  registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 80:5000
    volumes:
      - /var/lib/registry:/var/lib/registry
      - ./registry-config.yml:/etc/docker/registry/config.yml
    restart: always
  registry-ui:
    container_name: docker-registry-ui
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - URL=http://[URL]
      - DELETE_IMAGES=true
    restart: always
